# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20160920_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='courselinks',
        ),
    ]
