# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_user_courselinks'),
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='userlinks',
            field=models.ManyToManyField(to='registration.User'),
        ),
    ]
